parameters:
  - name: appVersion
    displayName: Update version of app
    type: string
    default: 2.4.0-beta
    values:
      - 2.4.0-beta

name: $(Year:yy).$(Month).$(DayOfMonth).$(rev:r)

pr: none
trigger: none

schedules:
  - cron: "0 3 * * 1"
    displayName: Publish iOS App
    branches:
      include:
        - main
pool:
  vmImage: 'macos-latest'

variables:
- group: AdaptiveCards-KVLink

steps:
  - bash: | 
     echo "Adaptive Version ${{ parameters.appVersion }}.$BUILD_NUMBER"
     xcrun agvtool new-version -all ${{ parameters.appVersion }}.$BUILD_NUMBER
    workingDirectory: source/ios/AdaptiveCards/ADCIOSVisualizer
    displayName: 'Bash - update sample app version'
    env:
      BUILD_NUMBER: $(Build.BuildNumber)


  - task: InstallAppleCertificate@2
    displayName: 'Install Certificates'
    inputs:
      certSecureFile: 'Certificates.p12' 
      certPwd: '$(P12password)'
      keychain: 'temp'

  - task: InstallAppleProvisioningProfile@1
    displayName: 'Install Provisioning Profile'
    inputs:
      provisioningProfileLocation: 'secureFiles'
      provProfileSecureFile: '2f82ca7c-d043-48c8-9298-7ca6331b08c7.mobileprovision'

  - template: templates/ios-build-template.yml
    parameters:
      sdk: iphoneos
      signingOption: auto
      packageApp: true
      configuration: Release

  - task: AppCenterDistribute@3
    inputs:
      serverEndpoint: 'AppCenter App iOS'
      appSlug: 'AdaptiveCards-Mobile/AdaptiveCards-iOS-Visualizer'
      appFile: '**/*.ipa'
      symbolsDsymFiles: '**/*.dSYM'
      symbolsIncludeParentDirectory: true
      releaseNotesOption: 'input'
      releaseNotesInput: 'Nightly Build from main'
      destinationType: 'groups'
